# **************************************** #
# This file is automatically generated !!! #
#        Please do not modify it !!!      #
# **************************************** #
import torch
import torch.nn as nn
import torch.nn.functional as F


class LBLNet18(nn.Module):

    def __init__(self):
        super(LBLNet18, self).__init__()
        self.conv41 = nn.Conv2d(32, 32, 3, 1, 1, bias=False)
        self.conv43 = nn.Conv2d(32, 32, 3, 1, 1, bias=False)
        self.fc47 = nn.Linear(512, 10, bias=False)

    def forward(self, x_40, ):
        x_41 = self.conv41(x_40)
        x_42 = F.relu(x_41)
        x_43 = self.conv43(x_42)
        x_44_0 = torch.add(x_43, x_40)
        x_44 = x_44_0
        x_45 = F.relu(x_44)
        x_46 = torch.flatten(x_45,start_dim=1)
        x_47 = self.fc47(x_46)
        output = x_47
        return output
