# **************************************** #
# This file is automatically generated !!! #
#        Please do not modfity it !!!      #
# **************************************** #
import torch
import torch.nn as nn
import torch.nn.functional as F


class LBLNet20(nn.Module):

    def __init__(self):
        super(LBLNet20, self).__init__()
        self.fc47 = nn.Linear(512, 10, bias=False)

    def forward(self, x_46, ):
        x_47 = self.fc47(x_46)
        output = x_47
        return output
