# **************************************** #
# This file is automatically generated !!! #
#        Please do not modify it !!!      #
# **************************************** #
import torch
import torch.nn as nn
import torch.nn.functional as F


class LBLNet12(nn.Module):

    def __init__(self):
        super(LBLNet12, self).__init__()
        self.conv27 = nn.Conv2d(8, 1, 1, 1, 0, bias=False)

    def forward(self, x_26, ):
        x_27 = self.conv27(x_26)
        output = x_27
        return output
