# **************************************** #
# This file is automatically generated !!! #
#        Please do not modfity it !!!      #
# **************************************** #
import torch
import torch.nn as nn
import torch.nn.functional as F


class LBLNet10(nn.Module):

    def __init__(self):
        super(LBLNet10, self).__init__()
        self.conv23 = nn.Conv2d(16, 8, 3, 1, 1, bias=False)
        self.conv25 = nn.Conv2d(8, 8, 3, 1, 1, bias=False)
        self.conv27 = nn.Conv2d(8, 1, 1, 1, 0, bias=False)

    def forward(self, x_22, ):
        x_23 = self.conv23(x_22)
        x_24 = F.relu(x_23)
        x_25 = self.conv25(x_24)
        x_26 = F.relu(x_25)
        x_27 = self.conv27(x_26)
        output = x_27
        return output
