# **************************************** #
# This file is automatically generated !!! #
#        Please do not modify it !!!      #
# **************************************** #
import torch
import torch.nn as nn
import torch.nn.functional as F


class LBLNet11(nn.Module):

    def __init__(self):
        super(LBLNet11, self).__init__()
        self.conv25 = nn.Conv2d(8, 8, 3, 1, 1, bias=False)
        self.conv27 = nn.Conv2d(8, 1, 1, 1, 0, bias=False)

    def forward(self, x_24, ):
        x_25 = self.conv25(x_24)
        x_26 = F.relu(x_25)
        x_27 = self.conv27(x_26)
        output = x_27
        return output
