# **************************************** #
# This file is automatically generated !!! #
#        Please do not modify it !!!      #
# **************************************** #
import torch
import torch.nn as nn
import torch.nn.functional as F


class LBLNet4(nn.Module):

    def __init__(self):
        super(LBLNet4, self).__init__()
        self.conv11 = nn.Conv2d(16, 32, 3, 1, 1, bias=False)
        self.conv13 = nn.Conv2d(32, 32, 3, 1, 1, bias=False)
        self.conv_tranpose15 = nn.ConvTranspose2d(64, 32, 2, 2, 0, bias=False)
        self.conv17 = nn.Conv2d(32, 16, 3, 1, 1, bias=False)
        self.conv19 = nn.Conv2d(16, 16, 3, 1, 1, bias=False)
        self.conv_tranpose21 = nn.ConvTranspose2d(32, 16, 2, 2, 0, bias=False)
        self.conv23 = nn.Conv2d(16, 8, 3, 1, 1, bias=False)
        self.conv25 = nn.Conv2d(8, 8, 3, 1, 1, bias=False)
        self.conv27 = nn.Conv2d(8, 1, 1, 1, 0, bias=False)

    def forward(self, x_10, x_9, x_4, ):
        x_11 = self.conv11(x_10)
        x_12 = F.relu(x_11)
        x_13 = self.conv13(x_12)
        x_14 = F.relu(x_13)
        x_15 = self.conv_tranpose15(x_14)
        x_16 = torch.cat([x_9, x_15, ], dim=1)
        x_17 = self.conv17(x_16)
        x_18 = F.relu(x_17)
        x_19 = self.conv19(x_18)
        x_20 = F.relu(x_19)
        x_21 = self.conv_tranpose21(x_20)
        x_22 = torch.cat([x_4, x_21, ], dim=1)
        x_23 = self.conv23(x_22)
        x_24 = F.relu(x_23)
        x_25 = self.conv25(x_24)
        x_26 = F.relu(x_25)
        x_27 = self.conv27(x_26)
        output = x_27
        return output
