# **************************************** #
# This file is automatically generated !!! #
#        Please do not modify it !!!      #
# **************************************** #
import torch
import torch.nn as nn
import torch.nn.functional as F


class LBLNet8(nn.Module):

    def __init__(self):
        super(LBLNet8, self).__init__()
        self.conv19 = nn.Conv2d(16, 16, 3, 1, 1, bias=False)
        self.conv_tranpose21 = nn.ConvTranspose2d(32, 16, 2, 2, 0, bias=False)
        self.conv23 = nn.Conv2d(16, 8, 3, 1, 1, bias=False)
        self.conv25 = nn.Conv2d(8, 8, 3, 1, 1, bias=False)
        self.conv27 = nn.Conv2d(8, 1, 1, 1, 0, bias=False)

    def forward(self, x_18, x_4, ):
        x_19 = self.conv19(x_18)
        x_20 = F.relu(x_19)
        x_21 = self.conv_tranpose21(x_20)
        x_22 = torch.cat([x_4, x_21, ], dim=1)
        x_23 = self.conv23(x_22)
        x_24 = F.relu(x_23)
        x_25 = self.conv25(x_24)
        x_26 = F.relu(x_25)
        x_27 = self.conv27(x_26)
        output = x_27
        return output
