# **************************************** #
# This file is automatically generated !!! #
#        Please do not modify it !!!      #
# **************************************** #
import torch
import torch.nn as nn
import torch.nn.functional as F


class MappedNet(nn.module):

    def __init__(self):
        super(MappedNet, self).__init__()
        self.fc2 = nn.Linear(14, 16, bias=False)
        self.fc3 = nn.Linear(14, 16, bias=False)
        self.fc4 = nn.Linear(14, 16, bias=False)
        self.fc5 = nn.Linear(14, 16, bias=False)
        self.fc8 = nn.Linear(13, 16, bias=False)
        self.fc9 = nn.Linear(13, 16, bias=False)
        self.fc10 = nn.Linear(13, 16, bias=False)
        self.fc11 = nn.Linear(13, 16, bias=False)
        self.fc14 = nn.Linear(14, 16, bias=False)
        self.fc15 = nn.Linear(14, 16, bias=False)
        self.fc16 = nn.Linear(14, 16, bias=False)
        self.fc17 = nn.Linear(14, 16, bias=False)
        self.fc20 = nn.Linear(13, 16, bias=False)
        self.fc21 = nn.Linear(13, 16, bias=False)
        self.fc22 = nn.Linear(13, 16, bias=False)
        self.fc23 = nn.Linear(13, 16, bias=False)

    def forward(self, x):
        x_0 = x
        x_1 = F.relu(x_0)
        x_2 = self.fc2(x_1)
        x_3 = self.fc3(x_1)
        x_4 = self.fc4(x_1)
        x_5 = self.fc5(x_1)
        x_6 = torch.cat([x_2,x_3,],dim=0)
        x_7 = torch.cat([x_4,x_5,],dim=0)
        x_8 = self.fc8(x_1)
        x_9 = self.fc9(x_1)
        x_10 = self.fc10(x_1)
        x_11 = self.fc11(x_1)
        x_12 = torch.cat([x_8,x_9,],dim=0)
        x_13 = torch.cat([x_10,x_11,],dim=0)
        x_14 = self.fc14(x_1)
        x_15 = self.fc15(x_1)
        x_16 = self.fc16(x_1)
        x_17 = self.fc17(x_1)
        x_18 = torch.cat([x_14,x_15,],dim=0)
        x_19 = torch.cat([x_16,x_17,],dim=0)
        x_20 = self.fc20(x_1)
        x_21 = self.fc21(x_1)
        x_22 = self.fc22(x_1)
        x_23 = self.fc23(x_1)
        x_24 = torch.cat([x_20,x_21,],dim=0)
        x_25 = torch.cat([x_22,x_23,],dim=0)
        x_26_0 = torch.add(x_6, x_12)
        x_26_1 = torch.add(x_26_0, x_18)
        x_26_2 = torch.add(x_26_1, x_24)
        x_26 = x_26_2
        x_27_0 = torch.add(x_7, x_13)
        x_27_1 = torch.add(x_27_0, x_19)
        x_27_2 = torch.add(x_27_1, x_25)
        x_27 = x_27_2
        x_28_0 = torch.add(x_26, x_27)
        x_28 = torch.div(x_28_0, 2)
        output = x_28
        return output
