/* **************************************** */
/* This file is automatically generated !!! */
/*        Please do not modify it !!!      */
/* **************************************** */

#pragma once
#include <vector>
#include "rcas_arch_cfg.h"
using namespace std;

typedef pair<int, int> node_id;

typedef struct {
	int		src_merge;
	node_id	dst_id;
	int		dst_task;
}Addr_encode;



enum Op_code { R_MVM, D_MVM, MaxPool, AvgPool, Add, Concat, Split, Identity };
enum DIR { W, B, E, S, NA };

typedef struct {
	int src_list;//(row*meshcol + col)*16+task
	pair<int, int> src_write_init_sride;//not used, for IO magic
	bool src_add_flag;//not used, for IO magic
}Src_struct;

typedef struct {
	int fin_size;
	int cin;
	int cout;
	int k_size;
	int stride;
	int padding;
	int rela_pe;//0~3
	int bitwise;
	int relu;
}Conv_struct;

typedef struct {
	bool vld;
	int task_id;
	pair<int,int> addr_base_offset;//global LB for assertion
	int credit_pix_len;
	vector<Src_struct> src_struct_list;
	int op_code;
	Conv_struct conv_attribute;
	vector<pair<int,int>> dst_chcast_list; //(row*meshcol + col)*16+task
										   //channel split within same pix
										   
}Task_Cfg_struct;


static Task_Cfg_struct task_cfg_list[16][8] = 
{
   //Core0_0 
   {
     {
        0, 
     },
     {
       1, 
       1, pair<int,int>(0, 32768), 1024, 
       {
         Src_struct{(1 * MESH_COL+0) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       Identity, 
       {
         Conv_struct{32, 32, 32, 0, 0, 0, NA, 0, 0},
       }, 
       {
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 4, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core0_1 
   {
     {
       1, 
       0, pair<int,int>(163840, 3072), 32, 
       {
         Src_struct{(0 * MESH_COL+0) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{32, 27, 32, 3, 1, 1, 1, 0, 1},
       }, 
       {
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 1, 32), 
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
       1, 
       1, pair<int,int>(131072, 32768), 32, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{32, 288, 32, 3, 1, 1, 3, 0, 1},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 1) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
       1, 
       2, pair<int,int>(98304, 32768), 1024, 
       {
         Src_struct{(1 * MESH_COL+1) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       Add, 
       {
         Conv_struct{32, 32, 32, 0, 0, 0, NA, 0, 1},
       }, 
       {
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 3, 32), 
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 4, 32), 
       },
     },
     {
       1, 
       3, pair<int,int>(65536, 32768), 32, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{32, 288, 32, 3, 1, 1, 0, 0, 1},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 0) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
       1, 
       4, pair<int,int>(32768, 32768), 1024, 
       {
         Src_struct{(0 * MESH_COL+0) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
       }, 
       Add, 
       {
         Conv_struct{32, 32, 32, 0, 0, 0, NA, 0, 1},
       }, 
       {
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 5, 32), 
         pair<int,int>((1 * MESH_COL + 0) * CORE_TASK_LIMIT + 1, 32), 
       },
     },
     {
       1, 
       5, pair<int,int>(0, 32768), 32, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 4, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{32, 32, 32, 1, 2, 0, 2, 0, 0},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core0_2 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core0_3 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core1_0 
   {
     {
       1, 
       0, pair<int,int>(41984, 32768), 32, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 3, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{32, 32, 32, 3, 1, 1, 1, 0, 0},
       }, 
       {
         pair<int,int>((0 * MESH_COL + 0) * CORE_TASK_LIMIT + 1, 32), 
       },
     },
     {
       1, 
       1, pair<int,int>(9216, 32768), 32, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 4, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{32, 288, 32, 3, 2, 1, 0, 0, 1},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 0) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
       1, 
       2, pair<int,int>(1024, 8192), 16, 
       {
         Src_struct{(1 * MESH_COL+0) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{16, 32, 32, 3, 1, 1, 3, 0, 0},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
       1, 
       3, pair<int,int>(512, 512), 128, 
       {
         Src_struct{(2 * MESH_COL+1) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
         Src_struct{(3 * MESH_COL+1) * CORE_TASK_LIMIT + 3, pair<int,int>(0, 64), 0}, 
       }, 
       Add, 
       {
         Conv_struct{4, 32, 32, 0, 0, 0, NA, 0, 1},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 0) * CORE_TASK_LIMIT + 4, 32), 
         pair<int,int>((2 * MESH_COL + 1) * CORE_TASK_LIMIT + 3, 32), 
       },
     },
     {
       1, 
       4, pair<int,int>(0, 512), 4, 
       {
         Src_struct{(1 * MESH_COL+0) * CORE_TASK_LIMIT + 3, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{4, 288, 32, 3, 1, 1, 2, 0, 1},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 1) * CORE_TASK_LIMIT + 1, 32), 
       },
     },
     {
       1, 
       5, pair<int,int>(74752, 8192), 512, 
       {
         Src_struct{(2 * MESH_COL+0) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
       }, 
       Identity, 
       {
         Conv_struct{16, 32, 32, 0, 0, 0, NA, 0, 0},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core1_1 
   {
     {
       1, 
       0, pair<int,int>(512, 32768), 32, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{32, 32, 32, 3, 1, 1, 1, 0, 0},
       }, 
       {
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
       1, 
       1, pair<int,int>(0, 512), 4, 
       {
         Src_struct{(1 * MESH_COL+0) * CORE_TASK_LIMIT + 4, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{4, 32, 32, 3, 1, 1, 0, 0, 0},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 1) * CORE_TASK_LIMIT + 3, 32), 
       },
     },
     {
       1, 
       2, pair<int,int>(33280, 2048), 256, 
       {
         Src_struct{(2 * MESH_COL+1) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
       }, 
       Identity, 
       {
         Conv_struct{8, 32, 32, 0, 0, 0, NA, 0, 0},
       }, 
       {
         pair<int,int>((3 * MESH_COL + 1) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core1_2 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core1_3 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core2_0 
   {
     {
       1, 
       0, pair<int,int>(40960, 8192), 512, 
       {
         Src_struct{(1 * MESH_COL+0) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 5, pair<int,int>(0, 64), 0}, 
       }, 
       Add, 
       {
         Conv_struct{16, 32, 32, 0, 0, 0, NA, 0, 1},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 1, 32), 
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 3, 32), 
       },
     },
     {
       1, 
       1, pair<int,int>(32768, 8192), 16, 
       {
         Src_struct{(2 * MESH_COL+0) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{16, 288, 32, 3, 1, 1, 1, 0, 1},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 0) * CORE_TASK_LIMIT + 5, 32), 
       },
     },
     {
       1, 
       2, pair<int,int>(24576, 8192), 16, 
       {
         Src_struct{(1 * MESH_COL+0) * CORE_TASK_LIMIT + 5, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{16, 32, 32, 3, 1, 1, 0, 0, 0},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 3, 32), 
       },
     },
     {
       1, 
       3, pair<int,int>(16384, 8192), 512, 
       {
         Src_struct{(2 * MESH_COL+0) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
         Src_struct{(2 * MESH_COL+0) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       Add, 
       {
         Conv_struct{16, 32, 32, 0, 0, 0, NA, 0, 1},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 4, 32), 
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 5, 32), 
       },
     },
     {
       1, 
       4, pair<int,int>(8192, 8192), 16, 
       {
         Src_struct{(2 * MESH_COL+0) * CORE_TASK_LIMIT + 3, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{16, 32, 32, 1, 2, 0, 3, 0, 0},
       }, 
       {
         pair<int,int>((3 * MESH_COL + 0) * CORE_TASK_LIMIT + 1, 32), 
       },
     },
     {
       1, 
       5, pair<int,int>(0, 8192), 16, 
       {
         Src_struct{(2 * MESH_COL+0) * CORE_TASK_LIMIT + 3, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{16, 288, 32, 3, 2, 1, 2, 0, 1},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 1) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core2_1 
   {
     {
       1, 
       0, pair<int,int>(3584, 2048), 8, 
       {
         Src_struct{(2 * MESH_COL+0) * CORE_TASK_LIMIT + 5, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{8, 32, 32, 3, 1, 1, 3, 0, 0},
       }, 
       {
         pair<int,int>((3 * MESH_COL + 1) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
       1, 
       1, pair<int,int>(1536, 2048), 8, 
       {
         Src_struct{(3 * MESH_COL+1) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{8, 32, 32, 3, 1, 1, 1, 0, 0},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 1) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
       1, 
       2, pair<int,int>(1024, 512), 4, 
       {
         Src_struct{(3 * MESH_COL+1) * CORE_TASK_LIMIT + 4, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{4, 32, 32, 3, 1, 1, 0, 0, 0},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 0) * CORE_TASK_LIMIT + 3, 32), 
       },
     },
     {
       1, 
       3, pair<int,int>(512, 512), 128, 
       {
         Src_struct{(1 * MESH_COL+1) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
         Src_struct{(1 * MESH_COL+0) * CORE_TASK_LIMIT + 3, pair<int,int>(0, 64), 0}, 
       }, 
       Add, 
       {
         Conv_struct{4, 32, 32, 0, 0, 0, NA, 0, 1},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 1) * CORE_TASK_LIMIT + 4, 512), 
       },
     },
     {
       1, 
       4, pair<int,int>(0, 512), 512, 
       {
         Src_struct{(2 * MESH_COL+1) * CORE_TASK_LIMIT + 3, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{1, 512, 10, 1, 1, 0, 2, 0, 0},
       }, 
       {
         pair<int,int>((3 * MESH_COL + 0) * CORE_TASK_LIMIT + 0, 10), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core2_2 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core2_3 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core3_0 
   {
     {
        0, 
     },
     {
       1, 
       1, pair<int,int>(0, 2048), 256, 
       {
         Src_struct{(2 * MESH_COL+0) * CORE_TASK_LIMIT + 4, pair<int,int>(0, 64), 0}, 
       }, 
       Identity, 
       {
         Conv_struct{8, 32, 32, 0, 0, 0, NA, 0, 0},
       }, 
       {
         pair<int,int>((3 * MESH_COL + 1) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core3_1 
   {
     {
       1, 
       0, pair<int,int>(8192, 2048), 256, 
       {
         Src_struct{(2 * MESH_COL+1) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
         Src_struct{(3 * MESH_COL+0) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
       }, 
       Add, 
       {
         Conv_struct{8, 32, 32, 0, 0, 0, NA, 0, 1},
       }, 
       {
         pair<int,int>((3 * MESH_COL + 1) * CORE_TASK_LIMIT + 1, 32), 
         pair<int,int>((3 * MESH_COL + 1) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
       1, 
       1, pair<int,int>(6144, 2048), 8, 
       {
         Src_struct{(3 * MESH_COL+1) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{8, 288, 32, 3, 1, 1, 1, 0, 1},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 1) * CORE_TASK_LIMIT + 1, 32), 
       },
     },
     {
       1, 
       2, pair<int,int>(4096, 2048), 256, 
       {
         Src_struct{(1 * MESH_COL+1) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
         Src_struct{(3 * MESH_COL+1) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       Add, 
       {
         Conv_struct{8, 32, 32, 0, 0, 0, NA, 0, 1},
       }, 
       {
         pair<int,int>((3 * MESH_COL + 1) * CORE_TASK_LIMIT + 3, 32), 
         pair<int,int>((3 * MESH_COL + 1) * CORE_TASK_LIMIT + 4, 32), 
       },
     },
     {
       1, 
       3, pair<int,int>(2048, 2048), 8, 
       {
         Src_struct{(3 * MESH_COL+1) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{8, 32, 32, 1, 2, 0, 0, 0, 0},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 0) * CORE_TASK_LIMIT + 3, 32), 
       },
     },
     {
       1, 
       4, pair<int,int>(0, 2048), 8, 
       {
         Src_struct{(3 * MESH_COL+1) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{8, 288, 32, 3, 2, 1, 3, 0, 1},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 1) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core3_2 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core3_3 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
};
static Task_Cfg_struct task_cfg_memout_new = { 
       1, 
       0, pair<int,int>(0, 512), 512, 
       {
         Src_struct{(2 * MESH_COL+1) * CORE_TASK_LIMIT + 4, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{1, 10, 10, 0, 0, 0, NA, 0, 0},
       }, 
       {
       },
};