from ..utils.python import PythonCode
from typing import Callable
from irtool.core import BaseIR
from irtool.tools import flatten_layers  # noqa
from mapper.device.CIMA import *

class TorchRTCodeGen(PythonCode):

    def __init__(self, ir, module_name='Inference', inputs=None, outputs=None):
        super().__init__()
        self.ir = ir
        self.module_name = module_name
        self.inputs = inputs
        self.outputs = outputs

    def gen_notes(self):
        yield '''
# **************************************** #
# This file is automatically generated !!! #
#        Please do not modify it !!!      #
# **************************************** #
'''

    def gen_imports(self):
        yield f'from cimruntime.CIMA.simulation.torch_utils import *'


    def gen_layers(self):

        yield from self.gen_notes()
        yield from self.gen_imports()

        yield
        yield

        self.ir.layers = dict(self.ir.iter_layers(deep=False, sorted=True))

        assert isinstance(self.ir, BaseIR), f'invalid IR type={type(self.ir)}'
        layers = self.ir.flatten_layers()

        # init inputs
        inp, oup = self.ir.get_io_layers(layers)

        self.all_node = {}

        self.layer_out_data_type = self.get_data_type(layers)

        self.next_layers = self.get_next_layer(layers)

        for name, layer in layers.items():

            if layer.type == 'input':
                c_ = 0
                for in_ in layer.inputs:
                    self.all_node[f'graph_input:{c_}'] = f'x_graph_input_{c_}'
                    c_ += 1
            elif layer.type == 'op':
                if len(layer.outputs) > 1:
                    c_ = 0
                    for in_ in layer.outputs:
                        self.all_node[f'{name}:{c_}'] = f'x_{name}_{c_}'
                        c_ += 1
                else:
                    self.all_node[f'{name}'] = f'x_{name}'

        # gen forward function
        for name, layer in layers.items():

            if layer.type == 'input':
                c_ = 0
                with self.indent():
                    s_ = ''
                    for in_ in layer.inputs:
                        t = self.all_node[f"graph_input:{c_}"]
                        s_ += f'{t}'
                        if c_ != len(layer.inputs):
                            s_ += f', '
                        c_ += 1
                 # generate function name
                yield f'''def {self.module_name}({s_} weights, activation_lut=None, PE_weight_noise=0, PE_out_noise=0, PE_in_noise=0, ADC_offset=0, device='cpu'):'''

                # gen constant
                constant = self.gen_constants(layers)
                with self.indent():
                    yield f'# Constant Values'
                    for cs in constant:
                        yield cs

            if layer.type == 'op':
                with self.indent():
                    # yield f'# Op Layers: {name}'
                    s_ = self.gen_layer(layer.op.op_id, name, layer)
                    if '\n' in s_:
                        s_1 = s_.split('\n')
                        c = 0
                        for s_2 in s_1:
                            if c != 0:
                                with self.indent(7):
                                    yield s_2
                            else:
                                yield s_2
                            c += 1
                    else:
                        yield s_

            if layer.type == 'output':
                with self.indent():
                    s_ = ''
                    for in_ in layer.inputs:
                        s_ += f'{self.all_node[in_.ref]}, '
                    yield f'return {s_}'

    def gen_constants(self, layers):
        constant_str = []
        for name, layer in layers.items():
            if layer.type == 'op' and layer.op.op_id in ['conv2d', 'matmul', 'fused_conv2d', 'fused_fc']:
                scale = layer.CIMA_calc_info.scale
                offset = layer.CIMA_calc_info.offset
                scale_shift_num = layer.CIMA_calc_info.scale_shift_num
                #     scale_shift_num = [scale_shift_num] * len(scale)
                scale_str_list = []
                offset_str_list = []
                scale_shift_num_str_list = []
                for i in range(len(scale)):
                    if scale[i] != 1 or offset[i] != 0:
                        scale_str_list.append(f'torch.tensor({scale[i]}).to(device)')
                        offset_str_list.append(f'torch.tensor({offset[i]}).to(device)')
                        scale_shift_num_str_list.append(f'{scale_shift_num[i]}')
                if scale_str_list != []:
                    scale_str = f'c_{name}_scale = ['
                    offset_str = f'c_{name}_offset = ['
                    scale_shift_num_str = f'c_{name}_scale_shift_num = ['
                    for i in range(len(scale_str_list)):
                        if i != 0:
                            scale_str += f"\n                      "
                            offset_str += f"\n                       "
                        scale_str += f"{scale_str_list[i]}, "
                        offset_str += f"{offset_str_list[i]}, "
                        scale_shift_num_str += f"{scale_shift_num_str_list[i]}, "

                    scale_str += ']'
                    offset_str += ']'
                    scale_shift_num_str += ']'
                    constant_str.append(scale_str)
                    constant_str.append(offset_str)
                    constant_str.append(scale_shift_num_str)
        return constant_str

    def get_data_type(self, layers):
        layer_data_type = {}
        for name, layer in layers.items():
            if layer.type == 'op':
                layer_data_type[name] = layer.CIMA_calc_info.data_type
        return layer_data_type

    def get_pre_layer(self, layers):
        ''''
        input: {layer_name:layer_object}
        return: {current_layer_name: pre_layer_name}
        '''
        prefix_layer = {}
        for name, layer in layers.items():
            if layer.type not in ['input']:
                prefix_layer[name] =  []
                # get_layer_ref(layers[name].inputs, layers, prefix_layer[name])
                for i in layer.inputs:
                    if 'graph_input' not in i.ref:
                        ref = i.ref
                        if ':' in ref:
                            ref = ref.split(':')[0]
                        # pre_layer = layers[ref]
                        #         prefix_layer[name].append(j.ref)
                        # else:
                        prefix_layer[name].append(ref)
                    else:
                        prefix_layer[name].append(i.ref)

        return prefix_layer

    def get_next_layer(self, layers):
        '''
        input: {layer_name:layer_object}
        return: {current_layer_name: next_layer_name}
        '''
        next_layer = {}
        pre_layer = self.get_pre_layer(layers)
        for k,v in pre_layer.items():
            for name in v:
                next_layer[name] = k
        return next_layer

    def gen_op(self, op_id, *args, **kwargs):
        fn = getattr(self, f'fn_gen_{op_id}', None)
        assert isinstance(fn, Callable), f'fn_gen_{op_id} is not a function'
        return fn(*args, **kwargs)

    def gen_layer(self, op_id, *args, **kwargs):
        return self.gen_op(op_id, *args, **kwargs)

    # conv

    def fn_gen_conv2d(self, layer_name, layer_info):
        # attr
        stride = layer_info.op.stride
        padding = layer_info.op.padding
        scale = layer_info.CIMA_calc_info.scale
        offset = layer_info.CIMA_calc_info.offset
        accumulate_shift_num = layer_info.CIMA_calc_info.accumulate_shift_num
        ADC_quant_level = layer_info.CIMA_calc_info.ADC_quant_level
        # pre layers
        pre_layers = layer_info.inputs[0].ref
        # data type
        if 'graph_input' in pre_layers:
            data_type = layer_info.CIMA_calc_info.data_type
        else:
            if ":" in pre_layers:
                pre_layers_ = pre_layers.split(':')[0]
            else:
                pre_layers_ = pre_layers
            data_type = self.layer_out_data_type[pre_layers_]
        # mappings
        for k,v in layer_info.CIMA_mapping_info.mappings.items():
            device_name = v.device
            break

        # scale first
        if layer_info.CIMA_calc_info.scale_first:
            scale_first = 'True'
        else:
            scale_first = 'False'

        s_ = ''
        if 'dmac' in device_name:

            if layer_info.op.op_id == 'fused_conv2d' and layer_info.op.relu != None:
                relu = 'True'
            else:
                relu = 'False'

            # CIMA_DMACConv_8bit(input_data, weight_data, *, stride=1, padding=0, scale=1, offset=0, scale_shift_num=0, accumulate_shift_num = 0)
            s_ += f"x_{layer_name} = CIMA_DMACConv_8bit({self.all_node[pre_layers]}, weights['{layer_name}.weight'], stride={stride}, padding={padding}, \n"
            if scale[0] != 1 or offset[0] != 0 or len(scale) > 1 or len(offset) > 1:
                # s_ += f"scale=bn_params['{layer_name}']['scale'], offset=bn_params['{layer_name}']['offset'],\nscale_shift_num=bn_params['{layer_name}']['scale_shift_num'], "
                s_ += f"scale=c_{layer_name}_scale, offset=c_{layer_name}_offset, scale_shift_num=c_{layer_name}_scale_shift_num, \n"
                s_ += f'jump_bn=False, '
            s_ += f"accumulate_shift_num={accumulate_shift_num}, relu={relu}, is_scale_first={scale_first})"

        elif 'cima-xb' in device_name:
            if layer_info.op.op_id == 'fused_conv2d' and layer_info.op.relu != None:
                relu = 'True'
            else:
                relu = 'False'

            next_layer = self.next_layers[layer_name]
            if next_layer == 'graph_output':
                next_data_type = data_type
            else:
                assert next_layer in self.layer_out_data_type.keys(), f'{next_layer}'
                next_data_type = self.layer_out_data_type[next_layer]

            if data_type ==  '4bit':

                func_name = 'CIMA_PEConv_4bIN_to_4bOUT'
                if next_data_type == '8bit':
                    func_name = 'CIMA_PEConv_4bIN_to_8bOUT'

                s_ += f"x_{layer_name} = {func_name}({self.all_node[pre_layers]}, weights['{layer_name}.weight'], stride={stride}, padding={padding}, ADC_quant_level={ADC_quant_level}, \n"
                if  scale[0] != 1 or offset[0] != 0 or len(scale) > 1 or len(offset) > 1:
                    # s_ += f"scale=bn_params['{layer_name}']['scale'], offset=bn_params['{layer_name}']['offset'],\nscale_shift_num=bn_params['{layer_name}']['scale_shift_num'], "
                    s_ += f"scale=c_{layer_name}_scale, offset=c_{layer_name}_offset, scale_shift_num=c_{layer_name}_scale_shift_num, "
                # else:
                    # s_ + f'jump_bn=True, '
                s_ += f"accumulate_shift_num={accumulate_shift_num}, \n"

                # noise
                s_ += f"DAC_noise=PE_in_noise, conductance_noise=PE_weight_noise, ADC_noise=PE_out_noise, ADC_offset=ADC_offset, relu={relu}, \n"
                s_ += f"device=device, is_scale_first={scale_first}, )"

            elif data_type == '8bit':
                func_name = 'CIMA_PEConv_8bIN_to_8bOUT'
                if next_data_type == '4bit':
                    func_name = 'CIMA_PEConv_8bIN_to_4bOUT'

                s_ += f"x_{layer_name} = {func_name}({self.all_node[pre_layers]}, weights['{layer_name}.weight'], stride={stride}, padding={padding}, ADC_quant_level={ADC_quant_level}, \n"
                print(f"{layer_name}")
                print("scale, offset:", scale, offset)
                if len(scale) > 1 or len(offset) > 1 or scale[0] != 1 or offset[0] != 0:
                    # s_ += f"scale=bn_params['{layer_name}']['scale'], offset=bn_params['{layer_name}']['offset'],\nscale_shift_num=bn_params['{layer_name}']['scale_shift_num'], "
                    s_ += f"scale=c_{layer_name}_scale, offset=c_{layer_name}_offset, scale_shift_num=c_{layer_name}_scale_shift_num, "
                # else:
                #     s_ + f'jump_bn=True, '
                s_ += f"accumulate_shift_num={accumulate_shift_num}, \n"

                # noise
                s_ += f"DAC_noise=PE_in_noise, conductance_noise=PE_weight_noise, ADC_noise=PE_out_noise, ADC_offset=ADC_offset, relu={relu}, \n"
                s_ += f"device=device, is_scale_first={scale_first}, )"
            else:
                raise ValueError(f'Message translated to English.')
        else:
            raise ValueError(f'Message translated to English.')

        return s_

    fn_gen_fused_conv2d = fn_gen_conv2d


    # conv

    def fn_gen_matmul(self, layer_name, layer_info):
        # attr
        scale = layer_info.CIMA_calc_info.scale
        offset = layer_info.CIMA_calc_info.offset
        accumulate_shift_num = layer_info.CIMA_calc_info.accumulate_shift_num
        ADC_quant_level = layer_info.CIMA_calc_info.ADC_quant_level
        # pre layers
        pre_layers = layer_info.inputs[0].ref
        # data type
        if 'graph_input' in pre_layers:
            data_type = layer_info.CIMA_calc_info.data_type
        else:
            if ":" in pre_layers:
                pre_layers_ = pre_layers.split(':')[0]
            else:
                pre_layers_ = pre_layers
            data_type = self.layer_out_data_type[pre_layers_]
        # mappings
        for k,v in layer_info.CIMA_mapping_info.mappings.items():
            device_name = v.device
            break

        # scale first
        if layer_info.CIMA_calc_info.scale_first:
            scale_first = 'True'
        else:
            scale_first = 'False'

        s_ = ''
        if 'dmac' in device_name:

            if layer_info.op.op_id == 'fused_fc' and layer_info.op.relu != None:
                relu = 'True'
            else:
                relu = 'False'

            # CIMA_DMACConv_8bit(input_data, weight_data, *, stride=1, padding=0, scale=1, offset=0, scale_shift_num=0, accumulate_shift_num = 0)
            s_ += f"x_{layer_name} = CIMA_DMACConv_8bit({self.all_node[pre_layers]}, weights['{layer_name}.weight'], \n"
            if scale[0] != 1 or offset[0] != 0 or len(scale) > 1 or len(offset) > 1:
                # s_ += f"scale=bn_params['{layer_name}']['scale'], offset=bn_params['{layer_name}']['offset'],\nscale_shift_num=bn_params['{layer_name}']['scale_shift_num'], "
                s_ += f"scale=c_{layer_name}_scale, offset=c_{layer_name}_offset, scale_shift_num=c_{layer_name}_scale_shift_num, \n"
                s_ += f'jump_bn=False, '
            s_ += f"accumulate_shift_num={accumulate_shift_num}, relu={relu}, is_scale_first={scale_first})"

        elif 'cima-xb' in device_name:
            if layer_info.op.op_id == 'fused_conv2d' and layer_info.op.relu != None:
                relu = 'True'
            else:
                relu = 'False'

            next_layer = self.next_layers[layer_name]
            if next_layer != 'graph_output':
                assert next_layer in self.layer_out_data_type.keys(), f'{next_layer}'
                next_data_type = self.layer_out_data_type[next_layer]

                if data_type ==  '4bit':
                    func_name = 'CIMA_PEConv_4bIN_to_4bOUT'
                    if next_data_type == '8bit':
                        func_name = 'CIMA_PEConv_4bIN_to_8bOUT'

                    s_ += f"x_{layer_name} = {func_name}({self.all_node[pre_layers]}, weights['{layer_name}.weight'], ADC_quant_level={ADC_quant_level}, accumulate_shift_num={accumulate_shift_num}, \n"
                    if scale[0] != 1 or offset[0] != 0 or len(scale) > 1 or len(offset) > 1:
                        # s_ += f"scale=bn_params['{layer_name}']['scale'], offset=bn_params['{layer_name}']['offset'],\nscale_shift_num=bn_params['{layer_name}']['scale_shift_num'], "
                        s_ += f"scale=c_{layer_name}_scale, offset=c_{layer_name}_offset, scale_shift_num=c_{layer_name}_scale_shift_num, \n"
                    # else:
                    #     s_ += f'jump_bn=True, '

                    # noise
                    s_ += f"DAC_noise=PE_in_noise, conductance_noise=PE_weight_noise, ADC_noise=PE_out_noise, ADC_offset=ADC_offset, relu={relu}, \n"
                    s_ += f"device=device, is_scale_first={scale_first}, )"
                elif data_type == '8bit':
                    func_name = 'CIMA_PEConv_8bIN_to_8bOUT'
                    if next_data_type == '4bit':
                        func_name = 'CIMA_PEConv_8bIN_to_4bOUT'

                    s_ += f"x_{layer_name} = {func_name}({self.all_node[pre_layers]}, weights['{layer_name}.weight'], ADC_quant_level={ADC_quant_level}, accumulate_shift_num={accumulate_shift_num}, \n"
                    if scale[0] != 1 or offset[0] != 0 or len(scale) > 1 or len(offset) > 1:
                        # s_ += f"scale=bn_params['{layer_name}']['scale'], offset=bn_params['{layer_name}']['offset'],\nscale_shift_num=bn_params['{layer_name}']['scale_shift_num'], "
                        s_ += f"scale=c_{layer_name}_scale, offset=c_{layer_name}_offset, scale_shift_num=c_{layer_name}_scale_shift_num, \n"
                    # else:
                    #     s_ += f'jump_bn=True, '
                    # s_ += f"accumulate_shift_num={accumulate_shift_num},\n"

                    # noise
                    s_ += f"DAC_noise=PE_in_noise, conductance_noise=PE_weight_noise, ADC_noise=PE_out_noise, ADC_offset=ADC_offset, relu={relu}, \n"
                    s_ += f"device=device, is_scale_first={scale_first}, )"
                else:
                    raise ValueError(f'Message translated to English.')
            else:
                if data_type ==  '4bit':
                    func_name = 'CIMA_PEConv_4bIN_to_4bOUT'

                    s_ += f"x_{layer_name} = {func_name}({self.all_node[pre_layers]}, weights['{layer_name}.weight'], ADC_quant_level={ADC_quant_level}, accumulate_shift_num={accumulate_shift_num}, \n"
                    if scale[0] != 1 or offset[0] != 0 or len(scale) > 1 or len(offset) > 1:
                        # s_ += f"scale=bn_params['{layer_name}']['scale'], offset=bn_params['{layer_name}']['offset'],\nscale_shift_num=bn_params['{layer_name}']['scale_shift_num'], "
                        s_ += f"scale=c_{layer_name}_scale, offset=c_{layer_name}_offset, scale_shift_num=c_{layer_name}_scale_shift_num, \n"
                    # else:
                    #     s_ += f'jump_bn=True, '

                    # noise
                    s_ += f"DAC_noise=PE_in_noise, conductance_noise=PE_weight_noise, ADC_noise=PE_out_noise, ADC_offset=ADC_offset, relu={relu}, \n"
                    s_ += f"device=device, is_scale_first={scale_first}, )"
                elif data_type == '8bit':
                    func_name = 'CIMA_PEConv_8bIN_to_8bOUT'

                    s_ += f"x_{layer_name} = {func_name}({self.all_node[pre_layers]}, weights['{layer_name}.weight'], ADC_quant_level={ADC_quant_level}, accumulate_shift_num={accumulate_shift_num}, \n"
                    if scale[0] != 1 or offset[0] != 0 or len(scale) > 1 or len(offset) > 1:
                        # s_ += f"scale=bn_params['{layer_name}']['scale'], offset=bn_params['{layer_name}']['offset'],\nscale_shift_num=bn_params['{layer_name}']['scale_shift_num'], "
                        s_ += f"scale=c_{layer_name}_scale, offset=c_{layer_name}_offset, scale_shift_num=c_{layer_name}_scale_shift_num, \n"
                    # else:
                    #     s_ += f'jump_bn=True, '
                    # s_ += f"accumulate_shift_num={accumulate_shift_num},\n"

                    # noise
                    s_ += f"DAC_noise=PE_in_noise, conductance_noise=PE_weight_noise, ADC_noise=PE_out_noise, ADC_offset=ADC_offset, relu={relu}, \n"
                    s_ += f"device=device, is_scale_first={scale_first}, )"
                else:
                    raise ValueError(f'Message translated to English.')
        else:
            raise ValueError(f'Message translated to English.')

        return s_

    fn_gen_fc = fn_gen_matmul
    fn_gen_fused_fc = fn_gen_matmul

    # transes

    def fn_gen_concat(self, layer_name, layer_info):

        s_ = '['
        c_ = 0
        for in_ in layer_info.inputs:
            s_ += f'{self.all_node[in_.ref]}'
            if c_ != len(layer_info.inputs) - 1:
                s_ += ', '
            c_ += 1
        s_ += ']'
        # attr
        axis = layer_info.op.axis
        return f'x_{layer_name} = CIMA_Concat({s_}, axis={axis})'

    # activate

    def fn_gen_relu(self, layer_name, layer_info):
        pre_layers = layer_info.inputs[0].ref
        return  f'x_{layer_name} = CIMA_Relu({self.all_node[pre_layers]})'


    def fn_gen_silu(self, layer_name, layer_info):
        # pre layers
        pre_layers = layer_info.inputs[0].ref
        # attr
        if ":" in pre_layers:
            pre_layers_ = pre_layers.split(':')[0]
        else:
            pre_layers_ = pre_layers
        data_type = self.layer_out_data_type[pre_layers_]

        if data_type == '4bit':
            return  f"x_{layer_name} = CIMA_SiLU_4bit({self.all_node[pre_layers]}, activation_lut['{layer_name}'])"
        elif data_type == '8bit':
            return  f"x_{layer_name} = CIMA_SiLU_8bit({self.all_node[pre_layers]}, activation_lut['{layer_name}'])"
        else:
            raise ValueError(f'Message translated to English.')
    # maxpool2d

    def fn_gen_max_pool2d(self, layer_name, layer_info):
        kernel = layer_info.op.kernel
        stride = layer_info.op.stride
        padding = layer_info.op.padding
        pre_layers = layer_info.inputs[0].ref
        return f'x_{layer_name} = CIMA_Maxpool2d({self.all_node[pre_layers]}, kernel_size={kernel}, stride={stride}, padding={padding})'


    fn_gen_maxpool2d = fn_gen_max_pool2d

    # avgpool2d

    def fn_gen_avg_pool2d(self, layer_name, layer_info):
        kernel = layer_info.op.kernel
        stride = layer_info.op.stride
        padding = layer_info.op.padding
        pre_layers = layer_info.inputs[0].ref
        shift_num = layer_info.CIMA_calc_info.accumulate_shift_num
        return f'x_{layer_name} = CIMA_Avgpool2d({self.all_node[pre_layers]}, kernel_size={kernel}, stride={stride}, padding={padding}, shift_num={shift_num}, device=device)'


    fn_gen_avgpool2d = fn_gen_avg_pool2d

    # add, mul
    def fn_gen_add(self, layer_name, layer_info):

        s_ = '['
        c_ = 0
        for in_ in layer_info.inputs:
            s_ += f'{self.all_node[in_.ref]}'
            if c_ != len(layer_info.inputs) - 1:
                s_ += ', '
            c_ += 1
        s_ += ']'

        # attr
        # data_type = layer_info.CIMA_calc_info.data_type
        # attr
        pre_layers = layer_info.inputs[0].ref
        if ":" in pre_layers:
            pre_layers_ = pre_layers.split(':')[0]
        else:
            pre_layers_ = pre_layers
        data_type = self.layer_out_data_type[pre_layers_]
        op_id = layer_info.op.op_id

        if data_type == '4bit':
            return f'x_{layer_name} = CIMA_Add_4bit({s_})'
        elif data_type == '8bit':
            return f'x_{layer_name} = CIMA_Add_8bit({s_})'
        else:
            raise ValueError(f'Message translated to English.')

    # add, mul
    def fn_gen_fused_add(self, layer_name, layer_info):

        in_s_ = '['
        c_ = 0
        for in_ in layer_info.inputs:
            in_s_ += f'{self.all_node[in_.ref]}'
            if c_ != len(layer_info.inputs) - 1:
                in_s_ += ', '
            c_ += 1
        in_s_ += ']'

        # attr
        # data_type = layer_info.CIMA_calc_info.data_type
        # attr
        pre_layers = layer_info.inputs[0].ref
        if ":" in pre_layers:
            pre_layers_ = pre_layers.split(':')[0]
        else:
            pre_layers_ = pre_layers
        data_type = self.layer_out_data_type[pre_layers_]

        op_id = layer_info.op.op_id
        split = layer_info.op.split
        silu = layer_info.op.silu
        relu = layer_info.op.relu

        if split != None:
            if silu != None:
                dim = layer_info.op.split.axis
                channel = layer_info.op.split.split
                s_ = ''
                c_ = 0
                for o in layer_info.outputs:
                    s_ += f'x_{layer_name}_{c_}'
                    if c_ != len(layer_info.outputs) - 1:
                        s_ += ', '
                    c_ += 1
                if data_type == '4bit':
                    return f"{s_} = CIMA_Add_SiLU_Split_4bit({in_s_}, activation_lut['{layer_name}'], {channel}, dim={dim})"
                elif data_type == '8bit':
                    return f"{s_} = CIMA_Add_SiLU_Split_8bit({in_s_}, activation_lut['{layer_name}'],  {channel}, dim={dim})"
                else:
                    raise ValueError(f'Message translated to English.')
            elif relu != None:
                dim = layer_info.op.split.axis
                channel = layer_info.op.split.split
                s_ = ''
                c_ = 0
                for o in layer_info.outputs:
                    s_ += f'x_{layer_name}_{c_}'
                    if c_ != len(layer_info.outputs) - 1:
                        s_ += ', '
                    c_ += 1
                if data_type == '4bit':
                    return f"{s_} = CIMA_Add_ReLU_Split_4bit({in_s_}, {channel}, dim={dim})"
                elif data_type == '8bit':
                    return f"{s_} = CIMA_Add_ReLU_Split_8bit({in_s_},  {channel}, dim={dim})"
                else:
                    raise ValueError(f'Message translated to English.')
            else:
                dim = layer_info.op.split.axis
                channel = layer_info.op.split.split
                s_ = ''
                c_ = 0
                for o in layer_info.outputs:
                    s_ += f'x_{layer_name}_{c_}'
                    if c_ != len(layer_info.outputs) - 1:
                        s_ += ', '
                    c_ += 1
                return f"{s_} = CIMA_Add_Split({in_s_}, {channel}, dim={dim})"
        elif silu != None:
            if data_type == '4bit':
                return f"x_{layer_name} = CIMA_Add_SiLU_4bit({in_s_}, activation_lut['{layer_name}'])"
            elif data_type == '8bit':
                return f"x_{layer_name} = CIMA_Add_SiLU_8bit({in_s_}, activation_lut['{layer_name}'])"
            else:
                raise ValueError(f'Message translated to English.')
        elif relu != None:
            if data_type == '4bit':
                return f"x_{layer_name} = CIMA_Add_ReLU_4bit({in_s_})"
            elif data_type == '8bit':
                return f"x_{layer_name} = CIMA_Add_ReLU_8bit({in_s_})"
            else:
                raise ValueError(f'Message translated to English.')
        else:
            raise ValueError(f'Message translated to English.')

    def fn_gen_mul_add(self, layer_name, layer_info):
        scale = layer_info.CIMA_calc_info.scale
        offset = layer_info.CIMA_calc_info.offset
        scale_shift_num = layer_info.CIMA_calc_info.scale_shift_num
        # data_type = layer_info.CIMA_calc_info.data_type
        pre_layers = layer_info.inputs[0].ref
        # attr
        if ":" in pre_layers:
            pre_layers_ = pre_layers.split(':')[0]
        else:
            pre_layers_ = pre_layers
        data_type = self.layer_out_data_type[pre_layers_]

        if data_type == '4bit':
            return f"x_{layer_name} = CIMA_Mul_Add_4bit({self.all_node[pre_layers]}, scale={scale}, offset={offset}, scale_shift_num={scale_shift_num})"
        elif data_type == '8bit':
            return f"x_{layer_name} = CIMA_Mul_Add_8bit({self.all_node[pre_layers]}, scale={scale}, offset={offset}, scale_shift_num={scale_shift_num})"
        else:
            raise ValueError(f'Message translated to English.')

    # resize

    def fn_gen_resize(self, layer_name, layer_info):

        pre_layer = layer_info.inputs[0].ref
        scale_factor = layer_info.op.scale[2:]
        return f"x_{layer_name} = CIMA_Resize({self.all_node[pre_layer]}, scale_factor={scale_factor})"



    # split
    def fn_gen_split(self, layer_name, layer_info):
        # attr
        dim = layer_info.op.axis
        channel = layer_info.op.split
        pre_layers = layer_info.inputs[0].ref

        s_ = ''
        c_ = 0
        for o in layer_info.outputs:
            s_ += f'x_{layer_name}_{c_}'
            if c_ != len(layer_info.outputs) - 1:
                s_ += ', '
            c_ += 1
        return f"{s_} = CIMA_Split({self.all_node[pre_layers]}, {channel}, dim={dim})"

    # split
    def fn_gen_fused_concat(self, layer_name, layer_info):
        # attr
        axis = layer_info.op.axis
        pre_layers = layer_info.inputs[0].ref
        split = layer_info.op.split
        silu = layer_info.op.silu
        # data type
        if ":" in pre_layers:
            pre_layers_ = pre_layers.split(':')[0]
        else:
            pre_layers_ = pre_layers
        data_type = self.layer_out_data_type[pre_layers_]
        # input
        in_s_ = '['
        c_ = 0
        for in_ in layer_info.inputs:
            in_s_ += f'{self.all_node[in_.ref]}'
            if c_ != len(layer_info.inputs) - 1:
                in_s_ += ', '
            c_ += 1
        in_s_ += ']'

        if split != None and silu != None:
            dim = layer_info.op.split.axis
            channel = layer_info.op.split.split
            s_ = ''
            c_ = 0
            for o in layer_info.outputs:
                s_ += f'x_{layer_name}_{c_}'
                if c_ != len(layer_info.outputs) - 1:
                    s_ += ', '
                c_ += 1
            if data_type == '4bit':
                return f"{s_} = CIMA_Concat_SiLU_Split_4bit({in_s_}, activation_lut['{layer_name}'], {axis}, {channel}, dim={dim})"
            elif data_type == '8bit':
                return f"{s_} = CIMA_Concat_SiLU_Split_8bit({in_s_}, activation_lut['{layer_name}'], {axis}, {channel}, dim={dim})"
            else:
                raise ValueError(f'Message translated to English.')
        elif split != None:
            dim = layer_info.op.split.axis
            channel = layer_info.op.split.split
            s_ = ''
            c_ = 0
            for o in layer_info.outputs:
                s_ += f'x_{layer_name}_{c_}'
                if c_ != len(layer_info.outputs) - 1:
                    s_ += ', '
                c_ += 1
            return f"{s_} = CIMA_Concat_Split({in_s_}, {axis}, {channel}, dim={dim})"
        elif silu != None:
            if data_type == '4bit':
                return f"x_{layer_name} = CIMA_Concat_SiLU_4bit({in_s_}, activation_lut['{layer_name}'], {axis})"
            elif data_type == '8bit':
                return f"x_{layer_name} = CIMA_Concat_SiLU_8bit({in_s_}, activation_lut['{layer_name}'], {axis})"
            else:
                raise ValueError(f'Message translated to English.')
        else:
            raise ValueError(f'Message translated to English.')

    # identity
    def fn_gen_identity(self, layer_name, layer_info):
        # attr
        pre_layers = layer_info.inputs[0].ref
        return f"x_{layer_name} = {self.all_node[pre_layers]}"

    # identity
    def fn_gen_flatten(self, layer_name, layer_info):
        # attr
        pre_layers = layer_info.inputs[0].ref
        start_dim = layer_info.op.start_dim
        return f"x_{layer_name} = torch.flatten({self.all_node[pre_layers]}, start_dim={start_dim})"

    # pad
    def fn_gen_pad(self, layer_name, layer_info):
        # attr
        pre_layers = layer_info.inputs[0].ref
        pads = layer_info.op.pads
        # IR attr to torch.Functional attr
        assert len(pads) % 2 == 0, f'Message translated to English.'
        pads_torch = []
        l = len(pads)//2
        for t in range(l-1, -1, -1):
            pads_torch.append(pads[t])
            pads_torch.append(pads[t+l])
        values = layer_info.op.value
        return f"x_{layer_name} = CIMA_Pad({self.all_node[pre_layers]}, pad={pads_torch}, value={values})"

    # type conversion
    def fn_gen_type_conversion(self, layer_name, layer_info):
        # attr
        in_dtype = layer_info.op.in_dtype
        out_dtype = layer_info.op.out_dtype
        assert in_dtype in ['4bit', '8bit']
        assert out_dtype in ['4bit', '8bit']
        pre_layers = layer_info.inputs[0].ref
        return f"x_{layer_name} = CIMA_{in_dtype}_to_{out_dtype}({self.all_node[pre_layers]})"
