/* **************************************** */
/* This file is automatically generated !!! */
/*        Please do not modify it !!!      */
/* **************************************** */

#pragma once
#include <vector>
#include "rcas_arch_cfg.h"
using namespace std;

typedef pair<int, int> node_id;

typedef struct {
	int		src_merge;
	node_id	dst_id;
	int		dst_task;
}Addr_encode;



enum Op_code { R_MVM, D_MVM, MaxPool, AvgPool, Add, Concat, Split, Identity };
enum DIR { W, B, E, S, NA };

typedef struct {
	int src_list;//(row*meshcol + col)*16+task
	pair<int, int> src_write_init_sride;//not used, for IO magic
	bool src_add_flag;//not used, for IO magic
}Src_struct;

typedef struct {
	int fin_size;
	int cin;
	int cout;
	int k_size;
	int stride;
	int padding;
	int rela_pe;//0~3
	int bitwise;
	int relu;
}Conv_struct;

typedef struct {
	bool vld;
	int task_id;
	pair<int,int> addr_base_offset;//global LB for assertion
	int credit_pix_len;
	vector<Src_struct> src_struct_list;
	int op_code;
	Conv_struct conv_attribute;
	vector<pair<int,int>> dst_chcast_list; //(row*meshcol + col)*16+task
										   //channel split within same pix
										   
}Task_Cfg_struct;


static Task_Cfg_struct task_cfg_list[9][8] = 
{
   //Core0_0 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core0_1 
   {
     {
       1, 
       0, pair<int,int>(27040, 784), 28, 
       {
         Src_struct{(0 * MESH_COL+0) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{28, 9, 32, 3, 1, 0, 1, 0, 1},
       }, 
       {
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 1, 32), 
       },
     },
     {
       1, 
       1, pair<int,int>(5408, 21632), 832, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       MaxPool, 
       {
         Conv_struct{26, 32, 32, 0, 0, 0, NA, 0, 0},
       }, 
       {
         pair<int,int>((0 * MESH_COL + 1) * CORE_TASK_LIMIT + 2, 32), 
       },
     },
     {
       1, 
       2, pair<int,int>(0, 5408), 13, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{13, 288, 32, 3, 2, 0, 3, 0, 1},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 1) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core0_2 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core1_0 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core1_1 
   {
     {
       1, 
       0, pair<int,int>(0, 1152), 192, 
       {
         Src_struct{(0 * MESH_COL+1) * CORE_TASK_LIMIT + 2, pair<int,int>(0, 64), 0}, 
       }, 
       Identity, 
       {
         Conv_struct{6, 32, 32, 0, 0, 0, NA, 0, 0},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 2) * CORE_TASK_LIMIT + 0, 32), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core1_2 
   {
     {
       1, 
       0, pair<int,int>(288, 1152), 192, 
       {
         Src_struct{(1 * MESH_COL+1) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       MaxPool, 
       {
         Conv_struct{6, 32, 32, 0, 0, 0, NA, 0, 0},
       }, 
       {
         pair<int,int>((1 * MESH_COL + 2) * CORE_TASK_LIMIT + 1, 288), 
       },
     },
     {
       1, 
       1, pair<int,int>(0, 288), 288, 
       {
         Src_struct{(1 * MESH_COL+2) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{1, 288, 48, 1, 1, 0, 3, 0, 1},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 2) * CORE_TASK_LIMIT + 0, 48), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core2_0 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core2_1 
   {
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
   //Core2_2 
   {
     {
       1, 
       0, pair<int,int>(0, 48), 48, 
       {
         Src_struct{(1 * MESH_COL+2) * CORE_TASK_LIMIT + 1, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{1, 48, 10, 1, 1, 0, 1, 0, 0},
       }, 
       {
         pair<int,int>((2 * MESH_COL + 0) * CORE_TASK_LIMIT + 0, 10), 
       },
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
     {
        0, 
     },
   },
};
static Task_Cfg_struct task_cfg_memout_new = { 
       1, 
       0, pair<int,int>(0, 48), 48, 
       {
         Src_struct{(2 * MESH_COL+2) * CORE_TASK_LIMIT + 0, pair<int,int>(0, 64), 0}, 
       }, 
       R_MVM, 
       {
         Conv_struct{1, 10, 10, 0, 0, 0, NA, 0, 0},
       }, 
       {
       },
};